apiVersion: v1
kind: ServiceAccount
metadata:
  name: papely-runner
  namespace: actions-runner-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: papely-deployer
  namespace: papely-qrcode
rules:
  - apiGroups: ["", "apps", "networking.k8s.io"]
    resources:
      - pods
      - services
      - deployments
      - replicasets
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: papely-deployer-binding
  namespace: papely-qrcode
subjects:
  - kind: ServiceAccount
    name: papely-runner
    namespace: actions-runner-system
roleRef:
  kind: Role
  name: papely-deployer
  apiGroup: rbac.authorization.k8s.io