apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: papely-ingress
spec:
  rules:
    - host: papely-qrcode.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: papely-service
                port:
                  number: 80
          - path: /upload
            pathType: Prefix
            backend:
              service:
                name: papely-backend
                port:
                  number: 80