name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/papely-qrcode .

      - name: Push da imagem
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/papely-qrcode

      # 🔥 BACKEND
      - name: Build backend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/papely-backend ./backend

      - name: Push backend
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/papely-backend