name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e push frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/papely-qrcode .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/papely-qrcode

      - name: Build e push backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/papely-backend ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/papely-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl

      - name: Add kubectl to PATH
        run: echo "$PWD" >> $GITHUB_PATH

      - name: Deploy
        run: kubectl apply -k k8s/overlays/dev

      - name: Restart deployments
        run: |
          kubectl rollout restart deployment dev-papely -n papely-qrcode
          kubectl rollout restart deployment dev-papely-backend -n papely-qrcode

      - name: Aguardar rollout
        run: |
          kubectl rollout status deployment/dev-papely -n papely-qrcode --timeout=120s
          kubectl rollout status deployment/dev-papely-backend -n papely-qrcode --timeout=120s
